name: CI

on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2.1.0

      - name: Install Dependencies
        run: yarn

      - name: Jest
        run: yarn test

      #  BUG - conflito do  prettier local com o do ci/cd
      # - name: Prettier
      #   run: yarn prettier:check

      - name: Lint
        run: yarn lint

      - name: Build
        run: npx tsc
